[versions]
agp = "8.5.2"
godot = "4.3.0.stable"
appcompat = "1.7.0"
material = "1.12.0"

[libraries]
godot = { module = "org.godotengine:godot", version.ref = "godot" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }

